name: Docs

# Trigger this Action when documentation source or the docs generator changes
on:
  push:
    branches:
      - main
    paths:
      - markdown/**
      - src/Hox.Docs/**
      - src/Hox/**
      - .github/workflows/docs.yml

# We need some permissions to publish to Github Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Generate the documentation
        run: dotnet run --project src/Hox.Docs -c Release -- --is-gh-pages
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  # GitHub Actions recommends deploying in a separate job.
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
