name: Samples Build

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - samples/**
      - global.json
      - Directory.Build.props
  pull_request:
    branches: [main]
    paths:
      - src/**
      - samples/**
      - global.json
      - Directory.Build.props

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v6
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"
      - run: dotnet restore samples/Samples.sln
      - run: dotnet build samples/Samples.sln --configuration Release --no-restore
